AWSTemplateFormatVersion: 2010-09-09
Description: >-
  To make sure the instances launched from Autoscaling are protected from
  Scale-in
Parameters:
  ami:
    Type: String
    Description: >-
      Enter a valid ami id keeping in mind the region this CFN template is being
      launched.
  InstanceType:
    Type: String
    Description: >-
      Enter valid instance Type depending on your resource requirement. Default
      is t2.micro.
  keypair:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: Choose a valid keypair
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup::Id'
    Description: Choose a security group to associate with launchconfiguration
  AutoScalingGroup:
    Type: String
    Description: Name of your AutoScaling Group
  IAMrole:
    Type: String
    Description: >-
      Enter a role to which an instance profile will be attached to give instances required perms to execute commands
Resources:
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref IAMrole
  launchConfig:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            C:\\restart.ps1:
              content: !Sub |
                Exit
                Start-Process PowerShell
              mode: "000644"
              owner: "root"
              group: "root"
          commands:
            install-chocolatey:
              command: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
            install-python:
              command: choco install python -y
              waitAfterCompletion: 70
            install-awscli:
              command: choco install awscli -y
              waitAfterCompletion: 70
            get-instance-id:
              command: $instanceId1=(New-Object System.Net.WebClient).DownloadString("http://169.254.169.254/latest/meta-data/instance-id”)
              waitAfterCompletion: 70
            scale-in-protection:
              command: aws autoscaling set-instance-protection --instance-ids $instanceID --auto-scaling-group-name ${AutoScalingGroup} --region ${AWS::Region} --protected-from-scale-in

    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref ami
      InstanceType: !Ref InstanceType
      KeyName: !Ref keypair
      SecurityGroups:
        - !Ref SecurityGroup
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              <powershell>
            - 'cfn-init.exe -v --stack '
            - !Ref 'AWS::StackName'
            - ' --region '
            - !Ref 'AWS::Region'
            - ' --resource launchConfig '
            - |+

            - |
              # Signal the status from cfn-init
            - 'cfn-signal.exe '
            - ' --stack '
            - !Ref 'AWS::StackName'
            - ' --resource AutoScalingGrp '
            - ' --region '
            - !Ref 'AWS::Region'
            - |+

            - |
              </powershell>
            - <persist>true</persist>
  AutoScalingGrp:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      AvailabilityZones: !GetAZs
        Ref: 'AWS::Region'
      LaunchConfigurationName: !Ref launchConfig
      MaxSize: '3'
      MinSize: '1'
